import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  plugins: [vue()],
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/main.ts'),
      name: 'ObsidianVuePlugin',
      fileName: 'main',
      formats: ['cjs']
    },
    rollupOptions: {
      external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab', 
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr'
      ],
      output: {
        banner: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY VITE\n*/',
        format: 'cjs',
        sourcemap: process.env.NODE_ENV !== 'production' 
      }
    },
    sourcemap: process.env.NODE_ENV !== 'production',
    outDir: './',
    emptyOutDir: false
  }
});
